---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oci-fss-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: fss.csi.oraclecloud.com
parameters:
  availabilityDomain: $(AV_DOMAIN)
  mountTargetSubnetOcid: $(PRIVATE_SUBNET_ID)
  encryptInTransit: "false"
