apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
