---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tor
  name: tor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor
  strategy: {}
  template:
    metadata:
      labels:
        app: tor
    spec:
      containers:
        - image: eu-frankfurt-1.ocir.io/frs4lzee0jfi/tor-privoxy
          name: tor-privoxy
          ports:
            - name: sock
              containerPort: 9050
            - name: control
              containerPort: 9051
            - name: privoxy
              containerPort: 8118
          resources: {}
      imagePullSecrets:
        - name: registry-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tor
  name: tor
  namespace: default
spec:
  ports:
    - name: sock
      port: 9050
      protocol: TCP
      targetPort: 9050
    - name: control
      port: 9051
      protocol: TCP
      targetPort: 9051
    - name: privoxy
      port: 8118
      protocol: TCP
      targetPort: 8118
  selector:
    app: tor
